#!/usr/bin/env bash
set -euo pipefail

ROOT="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")/.." && pwd)"
NOTIFY="$ROOT/config/quickshell/maho-notify"
THEME="$NOTIFY/NotifyTheme.qml"
CARD="$NOTIFY/NotificationCard.qml"
CENTER="$NOTIFY/NotificationCenter.qml"
ROW="$NOTIFY/HistoryRow.qml"
SHELL="$NOTIFY/shell.qml"
DECORATIONS="$ROOT/config/hypr/maho/appearance/decorations.lua"
RUNTIME="$ROOT/bin/maho-notify"

fail() { echo "FAIL: $*" >&2; exit 1; }
require_text() {
    local file="$1" needle="$2" message="$3"
    grep -Fq -- "$needle" "$file" || fail "$message"
}
reject_text() {
    local file="$1" needle="$2" message="$3"
    if grep -Fq -- "$needle" "$file"; then fail "$message"; fi
}

echo "=== Maho Notify glass family ==="
require_text "$THEME" 'function stableAccent' "stable wallpaper accent normalization missing"
require_text "$THEME" 'insetColor: mix(surfaceHigh, background, 0.36)' "Notify inset material drifted from Maho family"
require_text "$THEME" 'familyShell: mix(surfaceHigh, background, 0.54)' "Notify neutral shell material drifted"
require_text "$THEME" 'popupFill: alpha(mix(familyShell, accent, 0.030), 0.85)' "popup glass density regressed"
require_text "$THEME" 'centerFill: alpha(mix(centerShell, accent, 0.010), 0.86)' "center blur material density regressed"
require_text "$THEME" 'textBody: alpha(foreground, 0.84)' "body text hierarchy missing"
require_text "$THEME" 'textSecondary: alpha(foreground, 0.72)' "secondary text is too faint"
require_text "$THEME" 'shellRim: alpha(foreground, 0.068)' "center shell rim missing"
require_text "$THEME" 'shellTopSpecular: alpha(foreground, 0.050)' "quiet glass top reflection missing"
require_text "$THEME" 'toolbarFill:' "nested toolbar glass tier missing"
require_text "$THEME" 'sectionFill:' "nested history-well glass tier missing"
require_text "$THEME" 'controlFill:' "shared control tier missing"
require_text "$THEME" 'controlTopWash:' "raised control reflection missing"
require_text "$THEME" 'badgeActiveFill:' "active delivery badge tier missing"
require_text "$THEME" 'rowSelected:' "raised row tier missing"
require_text "$THEME" 'divider: alpha(foreground, 0.050)' "quiet divider tier missing"
reject_text "$CARD" 'theme.alpha(theme.surfaceHigh, 0.965)' "old opaque popup slab returned"
reject_text "$CENTER" 'theme.alpha(theme.surfaceHigh, 0.975)' "old opaque center slab returned"

echo "PASS"

echo "=== popup material and motion ==="
require_text "$CARD" 'color: theme.popupFill' "popup does not use shared glass shell"
require_text "$CARD" 'clip: true' "popup material is not radius-clipped"
require_text "$CARD" 'gradient: Gradient {' "popup material depth missing"
require_text "$CARD" 'theme.shellTopSpecular' "popup top reflection missing"
require_text "$CARD" 'theme.shellBottomShade' "popup lower material depth missing"
require_text "$CARD" 'color: theme.textBody' "popup body readability hierarchy missing"
require_text "$CARD" 'font.pixelSize: 15' "popup title hierarchy regressed"
require_text "$CARD" 'Behavior on scale' "popup hover motion missing"
require_text "$CARD" 'easing.type: Easing.OutCubic' "popup motion is not calm OutCubic"
require_text "$CARD" 'theme.actionFill' "actions do not use interactive glass tier"
require_text "$CARD" 'theme.controlPressed' "pressed feedback missing"
echo "PASS"

echo "=== center material and controls ==="
require_text "$CENTER" 'color: theme.centerFill' "center does not use shared glass shell"
require_text "$CENTER" 'clip: true' "center material is not radius-clipped"
require_text "$CENTER" 'theme.shellTopSpecular' "center top reflection missing"
reject_text "$CENTER" 'orientation: Gradient.Horizontal' "center reintroduced cross-panel stripe banding"
reject_text "$CARD" 'orientation: Gradient.Horizontal' "popup reintroduced cross-panel stripe banding"
reject_text "$NOTIFY/HistoryReplayCard.qml" 'orientation: Gradient.Horizontal' "replay popup reintroduced cross-panel stripe banding"
require_text "$CENTER" 'theme.shellAccentWash' "center restrained accent wash missing"
require_text "$CENTER" 'controlBody.containsMouse || center.controlMenuOpen' "focus summary glass interaction missing"
require_text "$CENTER" 'id: menuDismissLayer' "notification menus lack outside-click dismissal"
require_text "$CENTER" 'z: 480' "menu-dismiss backdrop no longer sits below popover surfaces"
require_text "$CENTER" 'id: controlChevronLane' "delivery card has no stable chevron lane"
require_text "$CENTER" 'width: 88' "delivery metadata lane width drifted"
require_text "$CENTER" 'opacity: controlBody.containsMouse || center.controlMenuOpen ? 1 : 0' "delivery chevron is not hover-only"
require_text "$CENTER" 'anchors.right: controlChevronLane.left' "delivery count is not pinned independently of the chevron"
require_text "$CENTER" 'x: controlBody.containsMouse || center.controlMenuOpen ? 0 : -4' "delivery chevron hover motion missing"
require_text "$THEME" 'menuFill:' "context-menu glass tier missing"
require_text "$CENTER" 'font.pixelSize: 26' "center title hierarchy regressed"
require_text "$CENTER" 'duration: center.shown ? 220 : 125' "accepted restrained center motion changed"
require_text "$CENTER" 'id: contentReveal' "center intro content transform missing"
require_text "$CENTER" 'y: center.shown ? 0 : -8' "center intro settle offset drifted"
require_text "$CENTER" 'duration: center.shown ? 245 : 110' "center intro settle timing drifted"
require_text "$CENTER" 'opacity: center.shown ? 1 : 0.42' "center intro content fade missing"
echo "PASS"

echo "=== persistent Edge-aware draggable notification center ==="
require_text "$SHELL" 'Quickshell.statePath("center-position.json")' "notification center position is not persisted"
require_text "$SHELL" 'if (centerPlacement.valid)' "persisted notification center placement is not authoritative"
require_text "$SHELL" 'surfaceX(centerOverlay.width, surface.width, centerMarginX)' "first-run center placement is not opposite Maho Edge"
require_text "$SHELL" 'drag.target: centerLoader.item' "notification center is not draggable"
require_text "$SHELL" 'onPressed: root.centerDragging = true' "notification center drag lifecycle missing"
require_text "$SHELL" 'follow final panel geometry so material depth does not change mid-drag' "drag glass continuity contract missing"
require_text "$SHELL" 'surface.controlMenuOpen = false' "delivery hover affordance can remain active across center reopen"
echo "PASS"

echo "=== history hierarchy ==="
require_text "$ROW" 'theme.rowUnread' "unread history glass tier missing"
require_text "$ROW" 'theme.rowHover' "history hover glass tier missing"
reject_text "$ROW" 'row.selected' "history reintroduced a second opaque selected state"
require_text "$ROW" 'theme.textPrimary' "history primary text hierarchy missing"
require_text "$ROW" 'theme.textBody' "history body readability hierarchy missing"
require_text "$ROW" 'theme.textFaint' "history metadata hierarchy missing"
require_text "$ROW" 'id: iconLane' "history icon optical lane missing"
require_text "$ROW" 'anchors.centerIn: parent' "history app icon is not centered in its optical lane"
require_text "$ROW" 'id: metaLane' "history metadata lane missing"
require_text "$ROW" 'width: 78' "history metadata lane width drifted"
require_text "$ROW" 'anchors.right: metaLane.left' "history text does not reserve metadata space"
require_text "$ROW" 'anchors.top: timeLabel.bottom' "history overflow control is not separated below timestamp"
require_text "$ROW" 'anchors.topMargin: 8' "history timestamp/overflow spacing drifted"
require_text "$ROW" 'id: actionLane' "history hover action lane missing"
require_text "$ROW" 'id: dotCluster' "history overflow dots do not share one optical center"
require_text "$ROW" 'width: 15' "history overflow dot cluster width drifted"
require_text "$ROW" 'width: 36' "history action lane width drifted"
require_text "$ROW" 'width: 30' "history overflow hover plate width drifted"
require_text "$ROW" 'height: 30' "history overflow hover plate height drifted"
reject_text "$ROW" 'gradient: Gradient {' "history rows reintroduced full-card gradient seams"
require_text "$ROW" 'scale: historyHover.hovered || row.menuOpen ? 1 : 0.96' "history overflow hover animation drifted"
require_text "$ROW" 'model: 3' "history overflow control lost its geometric three-dot mark"
require_text "$ROW" 'radius: 1.5' "history overflow dots are not geometrically centered primitives"
require_text "$ROW" 'font.pixelSize: 13' "history title hierarchy regressed"
require_text "$ROW" 'Behavior on color' "history transitions missing"
require_text "$ROW" 'Easing.OutCubic' "history motion is not calm OutCubic"
echo "PASS"

echo "=== popup glass material ==="
require_text "$SHELL" 'WlrLayershell.namespace: "maho-notify-popup"' "notification popup surface lacks a glass namespace"
require_text "$ROOT/config/hypr/maho/appearance/decorations.lua" 'name = "maho-notify-popup-material"' "notification popup compositor blur rule missing"
require_text "$ROOT/config/hypr/maho/appearance/decorations.lua" 'match = { namespace = "maho-notify-popup" }' "notification popup blur rule targets the wrong surface"
require_text "$ROOT/bin/maho-notify" 'maho_notify_popup_glass_rule' "runtime popup glass rule is not installed with Notify"
require_text "$NOTIFY/HistoryReplayCard.qml" 'theme.shellTopSpecular' "show-now replay card lost popup material depth"
require_text "$NOTIFY/HistoryReplayCard.qml" 'theme.shellInnerLine' "show-now replay card lacks popup specular edge"
echo "PASS"

echo "=== compositor blur lifecycle ==="
require_text "$SHELL" 'WlrLayershell.namespace: "maho-notify-center"' "Notify center layer namespace missing"
require_text "$DECORATIONS" 'namespace = "maho-notify-center"' "Hyprland Notify center blur rule missing"
require_text "$DECORATIONS" 'ignore_alpha = 0.16' "Notify direct-blur alpha threshold drifted"
require_text "$DECORATIONS" 'no_anim = true' "Notify center blur can compositor-fade into a dismissal footprint"
require_text "$RUNTIME" 'maho-notify-runtime-glass' "managed Notify runtime does not install scoped development blur"
require_text "$RUNTIME" 'set_hyprland_material_rule on' "managed Notify runtime does not enable scoped blur"
require_text "$RUNTIME" 'set_hyprland_material_rule off' "managed Notify runtime cannot retire scoped blur"
require_text "$SHELL" 'id: centerRevealDelay' "center reveal gate missing"
require_text "$SHELL" 'Loader {' "notification center visual tree is not lazy-loaded"
require_text "$SHELL" 'active: root.centerPresented' "hidden notification center tree remains resident"
require_text "$SHELL" 'function centerLoaded(): bool' "lazy center lifecycle is not observable"
require_text "$SHELL" 'theme: root.centerThemeRef' "lazy center does not receive the live Notify theme"
require_text "$SHELL" 'historyModel: root.centerHistoryModelRef' "lazy center does not receive the live history model"
reject_text "$SHELL" 'NotifyBackdrop {' "separate Notify blur carrier reintroduced drag/material drift"
reject_text "$SHELL" 'maho-notify-backdrop' "legacy Notify backdrop namespace reintroduced"
reject_text "$SHELL" 'BackgroundEffect.blurRegion' "rectangular background-effect blur can leak through rounded corners"
require_text "$SHELL" 'mask: Region { item: popupStack }' "popup input remains unconstrained"
require_text "$SHELL" 'mask: Region { item: centerLoader.item }' "center input remains unconstrained"
echo "PASS"

echo "ALL MAHO NOTIFY GLASS CONTRACTS PASS"
