#!/usr/bin/env bash
set -euo pipefail

ROOT="$(cd -- "$(dirname -- "$0")/.." && pwd)"
APP="$ROOT/apps/maho-polkit-agent"
SOURCE="$APP/src/main.c"
WRAPPER="$ROOT/bin/maho-polkit-agent"
UNIT="$ROOT/systemd/user/maho-polkit-agent.service"
TARGET="$ROOT/systemd/user/maho-hyprland-session.target"
SETUP="$ROOT/bin/maho-setup"
SESSION="$ROOT/bin/maho-session"
PKG="$ROOT/packaging/arch/PKGBUILD.in"
WINDOWING="$ROOT/config/hypr/maho/core/windowing.lua"

fail() { echo "FAIL: $*" >&2; exit 1; }
require_text() { grep -Fq -- "$2" "$1" || fail "$3"; }
reject_text() { grep -Fq -- "$2" "$1" && fail "$3" || true; }

echo "=== native PolicyKit authority boundary ==="
require_text "$SOURCE" 'G_DEFINE_TYPE(MahoPolkitListener' "native PolicyKit listener type missing"
require_text "$SOURCE" 'polkit_agent_listener_register(' "PolicyKit registration API missing"
require_text "$SOURCE" 'polkit_agent_listener_unregister(' "clean PolicyKit unregister missing"
require_text "$SOURCE" 'polkit_agent_session_new(' "PolicyKit authentication session missing"
require_text "$SOURCE" 'polkit_agent_session_initiate(' "PolicyKit conversation initiation missing"
require_text "$SOURCE" 'polkit_agent_session_response(' "responses do not return through PolicyKit"
require_text "$SOURCE" 'polkit_agent_session_cancel(' "PolicyKit cancellation missing"
reject_text "$SOURCE" 'pam_start(' "agent invented direct PAM authority"
reject_text "$SOURCE" 'sudo ' "agent introduced direct sudo privilege"
reject_text "$SOURCE" 'doas ' "agent introduced direct doas privilege"
reject_text "$SOURCE" 'pkexec ' "agent executes privileged commands"
reject_text "$SOURCE" 'system(' "agent accepts shell command execution"
reject_text "$SOURCE" 'popen(' "agent accepts subprocess command execution"
echo "PASS"

echo "=== lifecycle and fail-closed semantics ==="
require_text "$SOURCE" 'flock(fd, LOCK_EX | LOCK_NB)' "exactly-one process guard missing"
require_text "$SOURCE" 'POLKIT_ERROR_CANCELLED' "PolicyKit cancellation result missing"
require_text "$SOURCE" 'MAHO_POLKIT_BUS_NAME' "authority disappearance watch missing"
require_text "$SOURCE" 'process_alive(request->requester_pid)' "requesting process death check missing"
require_text "$SOURCE" 'maho_lock_active()' "secure Maho Lock cancellation gate missing"
require_text "$SOURCE" 'request_is_current(request)' "stale callback rejection missing"
require_text "$SOURCE" 'response_gate_consume' "exactly-one prompt response gate missing"
require_text "$SOURCE" 'responded_serial == serial' "duplicate response rejection missing"
require_text "$SOURCE" 'retry_session_idle' "wrong-password retry path missing"
require_text "$SOURCE" 'default_identity_index_for_uid' "deterministic identity selection missing"
require_text "$SOURCE" 'choice->uid != 0' "root can be silently preferred over another valid identity"
echo "PASS"

echo "=== secret handling ==="
require_text "$SOURCE" 'gtk_entry_set_visibility(self->entry, FALSE)' "password field is not secret by default"
require_text "$SOURCE" 'polkit_agent_session_response(request->session, response)' "secret is not sent directly to PolicyKit session"
require_text "$SOURCE" 'explicit_bzero(response' "in-memory response is not cleared after submission"
reject_text "$SOURCE" 'g_file_set_contents' "agent persists authentication data"
reject_text "$SOURCE" 'fprintf(' "agent contains an unreviewed generic logging sink"
reject_text "$WRAPPER" 'password' "wrapper handles authentication secrets"
echo "PASS"

echo "=== compact Maho UX ==="
require_text "$SOURCE" 'gtk_window_set_default_size(self->window, 430, -1)' "auth surface is not compact"
require_text "$SOURCE" 'g_object_ref_sink(self->window)' "top-level auth window has no explicit lifetime owner"
require_text "$SOURCE" 'g_clear_object(&self->window)' "top-level auth window ownership is not released on disposal"
require_text "$SOURCE" 'self->css_provider = gtk_css_provider_new()' "auth palette provider is not explicitly owned"
require_text "$SOURCE" 'gtk_style_context_remove_provider_for_display(' "auth palette provider is not removed with its window"
reject_text "$SOURCE" 'g_object_unref(provider)' "auth palette still accumulates unowned display providers"
require_text "$SOURCE" 'if (self->window == NULL)' "authentication requests do not rebuild a fresh top-level when needed"
require_text "$SOURCE" 'destroy_window(self);' "completed authentication does not tear down its GTK surface"
reject_text "$SOURCE" 'gtk_widget_set_visible(GTK_WIDGET(self->window), FALSE)' "completed authentication still preserves a stale hidden top-level"
require_text "$SOURCE" 'GDK_KEY_Escape' "Escape cancellation missing"
require_text "$SOURCE" 'gtk_entry_set_activates_default(self->entry, TRUE)' "Enter submit behavior missing"
require_text "$SOURCE" 'active.json' "wallpaper-derived Maho palette integration missing"
require_text "$SOURCE" 'Authenticate as:' "actual selected identity is not displayed"
require_text "$SOURCE" 'Requested by:' "requesting application/process presentation missing"
require_text "$WINDOWING" 'class = "^io[.]maho[.]PolkitAgent$"' "auth window is not matched by Maho window policy"
require_text "$WINDOWING" 'pin = true' "auth window can become stale on another workspace"
require_text "$WINDOWING" 'stay_focused = true' "auth window can lose focus while visible"
echo "PASS"

echo "=== session integration ==="
require_text "$UNIT" 'PartOf=maho-hyprland-session.target' "agent does not teardown with Maho session"
require_text "$UNIT" 'ConditionEnvironment=WAYLAND_DISPLAY' "agent can start outside graphical session"
require_text "$UNIT" 'Restart=on-failure' "agent crash recovery missing"
require_text "$UNIT" 'WantedBy=maho-hyprland-session.target' "agent is not owned by graphical target"
require_text "$TARGET" 'maho-polkit-agent.service' "graphical target does not start agent"
require_text "$SETUP" 'maho-polkit-agent.service' "runtime setup omits agent unit"
require_text "$SETUP" 'maho-polkit-agent' "runtime setup omits agent command"
require_text "$SESSION" 'maho-polkit-agent.service' "session reset/status omits agent"
echo "PASS"

echo "=== native build and deterministic core tests ==="
build="$(mktemp -d)"
trap 'rm -rf "$build"' EXIT
cmake -S "$APP" -B "$build" -G Ninja -DCMAKE_BUILD_TYPE=Release >/dev/null
cmake --build "$build" --parallel 2 >/dev/null
"$build/maho-polkit-agent" --self-test
bash -n "$WRAPPER" "$SETUP" "$SESSION"
require_text "$PKG" "'polkit'" "polkit runtime dependency missing"
require_text "$PKG" "'gtk4'" "GTK4 runtime dependency missing"
echo "PASS"
echo "PASS  Maho PolicyKit Agent V1 contracts"
