require("maho.core.windowing")
require("maho.core.input")
require("maho.appearance.decorations")
require("maho.core.binds")
pcall(require, "maho.integrations.clipboard")
require("maho.appearance.animations")
