#!/usr/bin/env python3
"""Generate Maho-owned, monitor-only Tetragon tracing policies.

The generated policy uses only Tetragon's documented tracing-policy interface.
It contains no upstream source code and never emits enforcement actions.
"""
from __future__ import annotations

import argparse
from enum import Enum
import json
from pathlib import Path
import re

_POLICY_NAME = re.compile(r"[a-z0-9](?:[a-z0-9-]{0,61}[a-z0-9])?")
_SAFE_ABSOLUTE_PATH = re.compile(r"/[A-Za-z0-9_+.,:@%/=~-]+(?:/[A-Za-z0-9_+.,:@%=-]+)*")


class TracePolicyScope(str, Enum):
    PID_FAMILY = "pid-family"
    BINARY_FAMILY = "binary-family"


def _policy_name(value: str) -> str:
    normalized = value.strip().lower().replace("_", "-")
    if _POLICY_NAME.fullmatch(normalized) is None:
        raise ValueError("Tetragon policy name must be DNS-label safe")
    return normalized


def _binary_path(value: str) -> str:
    if _SAFE_ABSOLUTE_PATH.fullmatch(value) is None:
        raise ValueError("trace binary path must be a simple absolute path")
    return value


def _selector_lines(
    scope: TracePolicyScope,
    *,
    pid: int | None,
    binary: str | None,
    indent: str,
) -> list[str]:
    if scope is TracePolicyScope.PID_FAMILY:
        if pid is None or isinstance(pid, bool) or pid < 1:
            raise ValueError("pid-family trace requires a positive host PID")
        if binary is not None:
            raise ValueError("pid-family trace does not accept a binary selector")
        return [
            f"{indent}- matchPIDs:",
            f"{indent}    - operator: In",
            f"{indent}      followForks: true",
            f"{indent}      isNamespacePID: false",
            f"{indent}      values:",
            f"{indent}        - {pid}",
        ]

    if binary is None:
        raise ValueError("binary-family trace requires an absolute binary path")
    if pid is not None:
        raise ValueError("binary-family trace does not accept a PID selector")
    binary = _binary_path(binary)
    return [
        f"{indent}- matchBinaries:",
        f"{indent}    - operator: In",
        f"{indent}      values:",
        f"{indent}        - {json.dumps(binary)}",
        f"{indent}      followChildren: true",
    ]


def generate_trace_policy(
    *,
    policy_name: str,
    scope: TracePolicyScope,
    pid: int | None = None,
    binary: str | None = None,
) -> str:
    name = _policy_name(policy_name)
    selector = _selector_lines(
        scope,
        pid=pid,
        binary=binary,
        indent="        ",
    )

    # File write-access activity. This is deliberately a hook-level access
    # observation, not a claim that content mutation completed successfully.
    file_selector = [
        *selector,
        "          matchArgs:",
        "            - index: 1",
        "              operator: Equal",
        "              values:",
        '                - "2"',
    ]

    network_selector = _selector_lines(
        scope,
        pid=pid,
        binary=binary,
        indent="        ",
    )

    lines = [
        "# Generated by MahoOS Guardian. Observation only.",
        "apiVersion: cilium.io/v1alpha1",
        "kind: TracingPolicy",
        "metadata:",
        f"  name: {name}",
        "spec:",
        "  kprobes:",
        "    - call: security_file_permission",
        "      syscall: false",
        "      message: Maho Guardian on-demand file write-access observation",
        "      args:",
        "        - index: 0",
        "          type: file",
        "        - index: 1",
        "          type: int",
        "      selectors:",
        *file_selector,
        "      tags:",
        "        - maho.guardian",
        "        - maho.trace.filesystem",
        "    - call: tcp_connect",
        "      syscall: false",
        "      message: Maho Guardian on-demand TCP connect-attempt observation",
        "      args:",
        "        - index: 0",
        "          type: sock",
        "      selectors:",
        *network_selector,
        "      tags:",
        "        - maho.guardian",
        "        - maho.trace.network",
        "",
    ]
    output = "\n".join(lines)

    # This is a hard contract, not merely a test convention.
    forbidden = ("matchActions:", "action:", "Sigkill", "Override", "Signal", "enforce")
    if any(token in output for token in forbidden):
        raise AssertionError("generated trace policy contains an enforcement primitive")
    return output


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(prog="guardian_tetragon_policy.py")
    parser.add_argument("--name", required=True)
    parser.add_argument("--scope", choices=[scope.value for scope in TracePolicyScope], required=True)
    parser.add_argument("--pid", type=int)
    parser.add_argument("--binary")
    parser.add_argument("--output", type=Path)
    args = parser.parse_args(argv)

    policy = generate_trace_policy(
        policy_name=args.name,
        scope=TracePolicyScope(args.scope),
        pid=args.pid,
        binary=args.binary,
    )
    if args.output:
        args.output.write_text(policy, encoding="utf-8")
    else:
        print(policy, end="")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
