#!/usr/bin/env python3
"""Render the isolated GTK3 material used by Maho Files.

Maho Files keeps Thunar as the file-management engine. This module only turns
Maho's active palette into a named GTK theme that can be applied to the Thunar
process with GTK_THEME=MahoFiles. It never edits the user's global GTK theme.
"""

from __future__ import annotations

import argparse
import json
import os
from pathlib import Path
import re
import sys

THEME_NAME = "MahoFiles"
HEX = re.compile(r"^#[0-9a-fA-F]{6}$")

FALLBACK = {
    "background": "#121112",
    "surface": "#1d1a1b",
    "surface_elevated": "#292526",
    "foreground": "#f0e9e8",
    "foreground_muted": "#bdb4b3",
    "accent": "#d3aaa8",
    "accent_soft": "#4a3637",
    "border": "#8e8484",
    "focus": "#d3aaa8",
    "shadow": "#000000",
    "critical": "#ffb4ab",
}


def _valid_color(value: object, fallback: str) -> str:
    text = str(value or "").strip()
    return text.lower() if HEX.fullmatch(text) else fallback


def palette_path() -> Path:
    cache = Path(os.environ.get("XDG_CACHE_HOME", Path.home() / ".cache"))
    return cache / "maho/theme/active.json"


def theme_root() -> Path:
    data = Path(os.environ.get("XDG_DATA_HOME", Path.home() / ".local/share"))
    return data / "themes" / THEME_NAME


def load_palette(path: Path) -> dict[str, str]:
    data: dict[str, object] = {}
    if path.is_file():
        try:
            loaded = json.loads(path.read_text(encoding="utf-8"))
        except (OSError, json.JSONDecodeError):
            loaded = {}
        if isinstance(loaded, dict):
            data = loaded

    semantic = data.get("semantic") if isinstance(data.get("semantic"), dict) else {}
    colors = data.get("colors") if isinstance(data.get("colors"), dict) else {}

    def role(name: str, legacy: str | None = None) -> str:
        candidate = semantic.get(name) if isinstance(semantic, dict) else None
        if candidate is None and legacy and isinstance(colors, dict):
            candidate = colors.get(legacy)
        return _valid_color(candidate, FALLBACK[name])

    return {
        "background": role("background", "background"),
        "surface": role("surface", "surface_container"),
        "surface_elevated": role("surface_elevated", "surface_container_high"),
        "foreground": role("foreground", "foreground"),
        "foreground_muted": role("foreground_muted", "muted"),
        "accent": role("accent", "primary"),
        "accent_soft": role("accent_soft", "surface_container_high"),
        "border": role("border", "outline"),
        "focus": role("focus", "primary"),
        "shadow": role("shadow"),
        "critical": role("critical", "error"),
    }


def render_css(palette: dict[str, str]) -> str:
    p = palette
    return f"""/* Generated by MahoOS. Maho Files only; do not use as a global GTK theme. */
@define-color maho_bg {p['background']};
@define-color maho_surface {p['surface']};
@define-color maho_surface_elevated {p['surface_elevated']};
@define-color maho_fg {p['foreground']};
@define-color maho_muted {p['foreground_muted']};
@define-color maho_accent {p['accent']};
@define-color maho_accent_soft {p['accent_soft']};
@define-color maho_border {p['border']};
@define-color maho_focus {p['focus']};
@define-color maho_shadow {p['shadow']};
@define-color maho_critical {p['critical']};

/* One continuous window material. Hyprland supplies the physical blur; GTK
 * supplies just enough neutral density and hierarchy for readable content. */
window,
window.background,
.background {{
    color: @maho_fg;
    background-color: alpha(@maho_bg, 0.62);
}}

window decoration {{
    border-radius: 18px;
    box-shadow:
        0 18px 46px alpha(@maho_shadow, 0.34),
        0 1px 0 alpha(@maho_fg, 0.11) inset;
}}

/* Calm top material. The highlight is intentionally broad and quiet rather
 * than a glossy pill so it stays consistent with accepted Maho glass. */
headerbar,
toolbar,
.primary-toolbar {{
    min-height: 44px;
    padding: 6px 10px;
    color: @maho_fg;
    background-color: alpha(@maho_surface, 0.50);
    background-image: linear-gradient(to bottom,
        alpha(@maho_fg, 0.085),
        alpha(@maho_fg, 0.020) 22%,
        alpha(@maho_surface, 0.00) 58%);
    border: 0;
    border-bottom: 1px solid alpha(@maho_border, 0.16);
    box-shadow: 0 1px 0 alpha(@maho_fg, 0.045) inset;
}}

headerbar:backdrop,
toolbar:backdrop {{
    background-color: alpha(@maho_surface, 0.43);
}}

/* Native buttons remain native actions; Maho only changes the material. */
headerbar button,
toolbar button,
.path-bar button,
.pathbar button {{
    min-height: 30px;
    min-width: 30px;
    padding: 4px 8px;
    margin: 1px 2px;
    color: @maho_fg;
    background-color: transparent;
    background-image: none;
    border: 1px solid transparent;
    border-radius: 11px;
    box-shadow: none;
    text-shadow: none;
    transition: 150ms ease;
}}

headerbar button:hover,
toolbar button:hover,
.path-bar button:hover,
.pathbar button:hover {{
    background-color: alpha(@maho_fg, 0.075);
    border-color: alpha(@maho_border, 0.12);
}}

headerbar button:checked,
toolbar button:checked,
.path-bar button:checked,
.pathbar button:checked {{
    background-color: alpha(@maho_accent_soft, 0.46);
    border-color: alpha(@maho_accent, 0.18);
}}

/* Premium close affordance. It is still GTK's real close action. */
headerbar button.titlebutton,
.titlebar button.titlebutton {{
    min-width: 30px;
    min-height: 30px;
    padding: 0;
    margin: 2px 3px;
    border-radius: 999px;
    color: @maho_fg;
    background-color: alpha(@maho_fg, 0.035);
    border: 1px solid alpha(@maho_fg, 0.07);
    box-shadow:
        0 1px 0 alpha(@maho_fg, 0.08) inset,
        0 5px 14px alpha(@maho_shadow, 0.11);
}}

headerbar button.titlebutton:hover,
.titlebar button.titlebutton:hover {{
    background-color: alpha(@maho_fg, 0.085);
    border-color: alpha(@maho_fg, 0.13);
}}

headerbar button.titlebutton.close,
.titlebar button.titlebutton.close {{
    min-width: 34px;
    min-height: 34px;
    color: @maho_fg;
    background-color: alpha(@maho_critical, 0.070);
    border-color: alpha(@maho_critical, 0.24);
    box-shadow:
        0 1px 0 alpha(@maho_fg, 0.11) inset,
        0 7px 18px alpha(@maho_shadow, 0.16);
}}

headerbar button.titlebutton.close:hover,
.titlebar button.titlebutton.close:hover {{
    color: white;
    background-color: alpha(@maho_critical, 0.28);
    border-color: alpha(@maho_critical, 0.68);
    box-shadow:
        0 1px 0 alpha(white, 0.18) inset,
        0 0 0 1px alpha(@maho_critical, 0.10),
        0 8px 22px alpha(@maho_shadow, 0.22);
}}

/* Location/path/search controls. */
entry,
searchentry,
.location-bar entry {{
    min-height: 32px;
    padding: 4px 10px;
    color: @maho_fg;
    caret-color: @maho_accent;
    background-color: alpha(@maho_surface_elevated, 0.40);
    border: 1px solid alpha(@maho_border, 0.16);
    border-radius: 12px;
    box-shadow:
        0 1px 0 alpha(@maho_fg, 0.035) inset,
        0 8px 20px alpha(@maho_shadow, 0.08);
}}

entry:focus,
searchentry:focus {{
    border-color: alpha(@maho_focus, 0.46);
    box-shadow:
        0 0 0 1px alpha(@maho_focus, 0.12),
        0 1px 0 alpha(@maho_fg, 0.05) inset;
}}

/* Side pane: denser than content but still the same glass object. */
.sidebar,
placessidebar,
stack.sidebar,
scrolledwindow.sidebar,
.sidebar .view {{
    color: @maho_fg;
    background-color: alpha(@maho_surface, 0.46);
    border: 0;
}}

.sidebar row,
placessidebar row {{
    min-height: 34px;
    margin: 2px 8px;
    padding: 2px 8px;
    border-radius: 10px;
    color: @maho_fg;
    background-color: transparent;
}}

.sidebar row:hover,
placessidebar row:hover {{
    background-color: alpha(@maho_fg, 0.055);
}}

.sidebar row:selected,
placessidebar row:selected {{
    color: @maho_fg;
    background-color: alpha(@maho_accent_soft, 0.52);
    box-shadow: 0 1px 0 alpha(@maho_fg, 0.04) inset;
}}

/* Content plane. No fake cards around files: rows/icons float in one clear
 * material and selection is the only intentionally raised state. */
scrolledwindow,
viewport,
paned,
.view,
treeview.view,
iconview.view,
flowbox {{
    color: @maho_fg;
    background-color: alpha(@maho_bg, 0.24);
    border: 0;
}}

treeview.view {{
    -GtkTreeView-horizontal-separator: 5;
    -GtkTreeView-vertical-separator: 4;
}}

treeview.view header button {{
    min-height: 30px;
    padding: 4px 8px;
    color: @maho_muted;
    background-color: alpha(@maho_surface, 0.36);
    border: 0;
    border-bottom: 1px solid alpha(@maho_border, 0.11);
    border-radius: 0;
    box-shadow: none;
}}

treeview.view:hover,
iconview.view:hover {{
    background-color: alpha(@maho_bg, 0.24);
}}

treeview.view:selected,
iconview.view:selected,
flowboxchild:selected {{
    color: @maho_fg;
    background-color: alpha(@maho_accent_soft, 0.48);
    border-radius: 9px;
}}

flowboxchild {{
    margin: 7px;
    padding: 7px;
    border-radius: 12px;
}}

flowboxchild:hover {{
    background-color: alpha(@maho_fg, 0.045);
}}

/* Bottom/status chrome should nearly disappear until useful. */
statusbar,
.statusbar {{
    min-height: 30px;
    padding: 3px 10px;
    color: @maho_muted;
    background-color: alpha(@maho_surface, 0.34);
    border-top: 1px solid alpha(@maho_border, 0.10);
}}

separator {{
    min-width: 1px;
    min-height: 1px;
    background-color: alpha(@maho_border, 0.12);
}}

/* Menus and dialogs stay GTK-native, only material/spacing changes. */
menu,
.menu,
.context-menu,
popover,
.background.popup {{
    color: @maho_fg;
    background-color: alpha(@maho_surface_elevated, 0.94);
    border: 1px solid alpha(@maho_border, 0.18);
    border-radius: 14px;
    box-shadow: 0 16px 38px alpha(@maho_shadow, 0.34);
}}

menuitem,
.menuitem,
popover modelbutton {{
    min-height: 30px;
    padding: 4px 10px;
    margin: 2px 5px;
    border-radius: 9px;
}}

menuitem:hover,
.menuitem:hover,
popover modelbutton:hover {{
    background-color: alpha(@maho_fg, 0.075);
}}

/* Quiet, narrow scrollbars. */
scrollbar {{
    background-color: transparent;
}}

scrollbar slider {{
    min-width: 5px;
    min-height: 34px;
    margin: 4px;
    border: 0;
    border-radius: 999px;
    background-color: alpha(@maho_muted, 0.24);
}}

scrollbar slider:hover {{
    background-color: alpha(@maho_fg, 0.38);
}}

tooltip {{
    color: @maho_fg;
    background-color: alpha(@maho_surface_elevated, 0.96);
    border: 1px solid alpha(@maho_border, 0.18);
    border-radius: 9px;
}}
"""


def write_theme(output: Path, palette_file: Path) -> tuple[Path, Path]:
    gtk_dir = output / "gtk-3.0"
    gtk_dir.mkdir(parents=True, exist_ok=True)
    css_path = gtk_dir / "gtk.css"
    index_path = output / "index.theme"

    palette = load_palette(palette_file)
    css_path.write_text(render_css(palette), encoding="utf-8")
    index_path.write_text(
        "[Desktop Entry]\n"
        "Type=X-GNOME-Metatheme\n"
        "Name=Maho Files\n"
        "Comment=Private GTK3 material for Maho Files\n",
        encoding="utf-8",
    )
    return css_path, index_path


def doctor(palette_file: Path, output: Path) -> int:
    palette = load_palette(palette_file)
    css = render_css(palette)
    checks = {
        "palette": all(HEX.fullmatch(value) for value in palette.values()),
        "isolated_theme": output.name == THEME_NAME,
        "translucent_window": "alpha(@maho_bg, 0.62)" in css,
        "premium_close": "button.titlebutton.close:hover" in css,
        "native_views": "treeview.view" in css and "iconview.view" in css,
    }
    failed = False
    for name, ok in checks.items():
        print(f"{'PASS' if ok else 'FAIL'}  {name}")
        failed = failed or not ok
    return 1 if failed else 0


def parser() -> argparse.ArgumentParser:
    root = argparse.ArgumentParser(description=__doc__)
    sub = root.add_subparsers(dest="command")

    render = sub.add_parser("render")
    render.add_argument("--palette", type=Path, default=palette_path())
    render.add_argument("--output", type=Path, default=theme_root())

    check = sub.add_parser("doctor")
    check.add_argument("--palette", type=Path, default=palette_path())
    check.add_argument("--output", type=Path, default=theme_root())

    return root


def main(argv: list[str]) -> int:
    args = parser().parse_args(argv)
    command = args.command or "render"
    if command == "render":
        css, index = write_theme(args.output, args.palette)
        print(css)
        print(index)
        return 0
    if command == "doctor":
        return doctor(args.palette, args.output)
    return 2


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
